### ISSUE TITLE
Story 15 : scanner un QRCode géant afin d’accéder à un texte 

### ISSUE THREAD

**Issue by javamind** [Dev-Mind/numeric-wall#15]
Story 15 : En tant que public je veux pouvoir scanner un QRCode géant afin d’accéder à un texte qui
m’expliquer le thème (parcours) sous­jacent à ce QRCode.

**Comment by acrepet** [comment]
Ce texte sera fourni en amont par C. Berton. Le texte explicitera:
- le personnage du parcours
- le thème associé
- l'EMSE par rapport au thème
- les enjeux

**Comment by javamind** [comment]
On peut maintenant scanner reste à permettre d'associer un texte a une catégorie
