### ISSUE TITLE
consulter en texte dans "Mes productions"

### ISSUE THREAD

**Issue by acrepet** [Dev-Mind/numeric-wall#37]
il est possible de modifier ou supprimer un texte dans l'écran /myproductions. Il serait interessant de pouvoir simplement le visualiser

**Comment by javamind** [comment]
Il est modifiable tant qu'il n'est pas à l'état Validé. Un admin peut changer l'état des textes. Un admin a également le droit de modifier une production validée

**Comment by acrepet** [comment]
la question n'est pas sur la modif mais la consultation

**Comment by javamind** [comment]
Alors là je ne comprends pas ce que tu veux dire. La règle est quand un texte est à l'état Validé il est en mode visualisation seule pour un étudiant mais en modification pour un admin. 
Dans ton cas les textes étaient à l'état Pending

**Comment by acrepet** [comment]
Ok ça roule
