### ISSUE TITLE
coment accéder au contenu

### ISSUE THREAD

**Issue by acrepet** [Dev-Mind/numeric-wall#38]
sur l'écran /bigqrcode je ne sais comment accéder au texte en cliquant sur un petit qrcode. Quand je passe la souris sur un petit qrcode, il apparait bleu (scintillement) mais quand je clique rien ne passe. Comment distinguer un qrcode actif (=avec texte derrière) d'un qrcode non actif?

**Comment by javamind** [comment]
Cette partie restitution n'est pas faite #13 et #15 car ce n'est pas le plus compliqué et j'ai priorisé par criticité d'un point de vue complexité

**Comment by acrepet** [comment]
OK. Mais tu t'es trompé de Story. Je parlais de #14 et non pas #13 et #15

**Comment by javamind** [comment]
Comme la #14 est faite je clos
