### ISSUE TITLE
coment accder aux fonctions d'admin?

### ISSUE THREAD

**Issue by acrepet** [Dev-Mind/numeric-wall#39]
quand j'accède à la partie sécurisée de l'application, je peux:
-ajouter un nouveau contenu
-voir mes productions

j'ai donc à priori un profil participant

mais comment tester avec un profil "administrateur"?

**Comment by javamind** [comment]
Quel est ton matricule dans le CAS que je te rajoute dans les scripts d'init pour être admin ?

**Comment by javamind** [comment]
Pour le moment il faut modifier à la main en base de données le profil dans la table UserProfil et utiliser le profil 2 au lieu de 3. Pour le moment le user se nomme user.fake

**Comment by acrepet** [comment]
je n'ai pas de table UserProfil, juste User_Authority

**Comment by acrepet** [comment]
j'ai bien vu le user user.fake dans la table User par contre

**Comment by acrepet** [comment]
ok bon j'en ai déduis qu'il fallait rajouter une ligne dans la table User_Authority:
 insert into User_Authority values(1,2);
