### ISSUE TITLE
Pour toutes les actions j'ai un warn dans les logs

### ISSUE THREAD

**Issue by acrepet** [Dev-Mind/numeric-wall#42]
WARN 3466 --- [nio-8080-exec-2] f.e.e.security.DevAuthenticationFilter   : DevAuthenticationFilter class should be only use in development

**Comment by javamind** [comment]
Normal pour rappeler qu'on est sur une conf de dev et non relié au CAS

**Comment by acrepet** [comment]
Ok ça roule

**Comment by acrepet** [comment]
pour lancer l'appli en mode "server"
rajouter --spring.profiles.active=server à la ligne de commande de lancement
