### ISSUE TITLE
Mauvais affichage de l'état d'une production

### ISSUE THREAD

**Issue by acrepet** [Dev-Mind/numeric-wall#43]
quand mon texte est "en attente" mais l'icone "Validé" est affichée
et vis-versa : quand mon texte est "Validé " mais l'icone "en attente" est affichée

**Comment by javamind** [comment]
D'où les incompréhensions dans les issues :smile:

**Comment by acrepet** [comment]
Non c'est autre chose ; y'a une inversion d'icône mais EN PLUS on ne voit qu'un état à la fois (l'autre issue)
