### ISSUE TITLE
Prévoir de voir toutes les productions

### ISSUE THREAD

**Issue by acrepet** [Dev-Mind/numeric-wall#44]
pour le moment je ne vois les productions avec un filtre sur l'état (ex : que celles qui sont validées, etc.), il serait bien de pouvoir toutes les voir

**Comment by javamind** [comment]
Il faut être admin pour ça. Pour le moment comme tu n'est pas reliée au CAS tu n'as qe les droits d'un étudiant

**Comment by javamind** [comment]
Après il faut jouer sur les critères de tri. Par défaut tu vois toutes les productions à l'état Pending. Ensuite tu peux jouer sur les critères de recherche pour affiner

**Comment by acrepet** [comment]
Je suis admin après bidouille en base. Je ne vois pas toutes les prod à la fois puisque radio bouton sur le critère état dans les critères (un seul état possible)

**Comment by javamind** [comment]
J'ai fait ça pour ne pas tout intérroger d'un coup mais surtout pour simplifier la requête derrière. Je n'ai rien eu besoin de recoder par rapport à mes services initiaux. Si ça pose problème on la laisse ouverte. Je pensais que le besoin n°1 était de valider les productions le plus vite possile et qu'à terme elles seraient toutes validées

**Comment by acrepet** [comment]
non c'est on on laisse comme ça
