### ISSUE TITLE
[EVOL] Baisser la permission du taux d’erreur pour la génération des QRCODEs

### ISSUE THREAD

**Issue by acrepet** [Dev-Mind/numeric-wall#48]
Ceci pour avoir moins de carrés dans le QRCODE. Il s’avère qu’il y aura moins de 300 productions par Parcours.
Mais il est préférabe de perdre en permission du taux d’erreur pour les "petits" QRCODEs, afin de pouvoir les imprimer sur les badges de F. Grimaud

**Comment by javamind** [comment]
Ce n'est pas fait suite au mail de vendredi 
Par défaut on reste avec des QR code en qualité optimale permettant d'améliorer le scan et de fournir 600 positions
Une parade a été faite pour le pett QRCode permettant d'accéder à une catégorie aléatoirement
