### ISSUE TITLE
[EVOL] Il doit être possible de consulter une production même si elle est validée

### ISSUE THREAD

**Issue by acrepet** [Dev-Mind/numeric-wall#51]

**Comment by acrepet** [comment]
we can't see our production in a consulation way, we only can see them in a update way.
We have to see our production in a consulation way, to validate the rendering (markdown)

**Comment by javamind** [comment]
The writer see his productions in a consultation way 
![image](https://cloud.githubusercontent.com/assets/1812822/12244310/5f34cc84-b8a3-11e5-82c3-8d8f704758b2.png)

If you have a profile `admin`, yes you have the right to update all the productions and this is your initial request

**Comment by javamind** [comment]
Can you try with another profile ?
