### ISSUE TITLE
[EVOL] ajouter une page avec redirection aléatoire vers un texte

### ISSUE THREAD

**Issue by acrepet** [Dev-Mind/numeric-wall#53]
Idée proposée par F. Grimaud après la réunion du 07/01:
Puisqu'il n'y aura plus de Mur Physique (à savoir le fait de coller des badges QRCODES sur les QRCODES géants), il faut trouver un lien avec l'atelier Performance Lab de fabrication des badges.
Pourquoi il n'y aura plus de Mur Physique? Parce que cela parait compliqué d'un point de vue organisationnel d'aller coller les badges à un endroit bien précis du QRCODE géant, et pas vraiment pertinent puisque le produit "Mur Physique" n'est plus exposé au Musée d'Art et d'Industrie.

Pour faire un lien donc entre l'atelier de création des badges et le Mur Numérique, et de privilégier une organisation simple de l'atelier, l'idée est d'imprimer un seul QRCODE qui pointerait toujours vers la même URL, par exemple : http://ewall.mines-stetienne.fr/random
Cette page ferait une redirection aléatoire vers un texte, ceci pour donner une idée au public du type de production.

Avec cette simplification, il n’est plus nécessaire de générer tous les QRCODES. Un seul est à générer.

**Comment by javamind** [comment]
URL to generate QR code is for example (in dev) http://localhost:3000/api/public/qrcode/random

**Comment by acrepet** [comment]
en prod : https://ewall.mines-stetienne.fr/api/public/qrcode/random

cette API pointe vers un QRCODE qui lui pointe vers une URL de type https://ewall.mines-stetienne.fr/e-wall/r
