### ISSUE TITLE
the Category change doesn't work

### ISSUE THREAD

**Issue by acrepet** [Dev-Mind/numeric-wall#58]
When I want to change the Category of a production, the "Enregistrer" button in inative, so it's not possile to validate the Category change

**Comment by javamind** [comment]
The button is inactive when you have an error in your form
Author and content are presents ?

**Comment by acrepet** [comment]
No error, yes the other fields are ok
Le 11 janv. 2016 11:20 PM, "Guillaume EHRET" notifications@github.com a
écrit :

**Comment by acrepet** [comment]
OK, I believed that this feature change the Category of the text. It's not the case!
