### ISSUE TITLE
nothing apperas with IE

### ISSUE THREAD

**Issue by acrepet** [Dev-Mind/numeric-wall#74]
With IE (latest versions -the screenshot is with the version 11) we can't access to the application!

It's petty because 50% of the workstattions of Ecole des Mines has IE.

On the Bootstrap doc we can read that there is compatibility:
http://getbootstrap.com/getting-started/

![ie](https://cloud.githubusercontent.com/assets/544206/12390434/463b3a8c-bde0-11e5-87fd-95ab1aa80809.png)

**Comment by javamind** [comment]
We use flexbox to display application on the different devices 
Normally we can use some features on IE 11 : http://caniuse.com/#search=flex
We need to find polyfills

You don't use Edge on windows ?

**Comment by acrepet** [comment]
No we don't use Edge, but we aren't reaching the compatibility with old versions of IE. Just the latest ones : IE10/11

**Comment by acrepet** [comment]
Perhaps it's juste a display bug

**Comment by javamind** [comment]
Which version of Windows do you used ? 
https://support.microsoft.com/en-us/lifecycle#gp/Microsoft-Internet-Explorer

**Comment by acrepet** [comment]
Mainly Internet Explorer 11. And some 10
