### ISSUE TITLE
[IE 11] Font problem on the /wall page

### ISSUE THREAD

**Issue by amomm** [Dev-Mind/numeric-wall#78]
The letters writing FUTUR are small and black on the /wall page using Internet Explorer 11
![futur](https://cloud.githubusercontent.com/assets/11678149/12582820/af0ea372-c43f-11e5-9cc7-8876e99161e0.png)

**Comment by javamind** [comment]
This feature is alreday fixed but not installed on the server for the moment 
See d29f6f625965b4836957e7efca80ae5f215329c2
