### ISSUE TITLE
[IE11] Productions not showing on the myproductions page

### ISSUE THREAD

**Issue by amomm** [Dev-Mind/numeric-wall#80]
Your own productions are not shown on the /myproductions page
![prod](https://cloud.githubusercontent.com/assets/11678149/12583484/4fc4521e-c443-11e5-80db-98c8cc76c48c.png)

**Comment by javamind** [comment]
Non reproduit
![image](https://cloud.githubusercontent.com/assets/1812822/12586624/4f505e14-c451-11e5-896a-ef19b09ea7bb.png)

**Comment by javamind** [comment]
Problème de cache de données uniquement pour les admins. Maintenant je vide le cache après chaque ajout ou suppression
