### ISSUE TITLE
l'accès à certaines api ne marche plus

### ISSUE THREAD

**Issue by acrepet** [Dev-Mind/numeric-wall#81]
si je clique sur un titre de parcours une fois OK
Si je recharge l'URL (ex : https://ewall.mines-stetienne.fr/e-wall/i/ pour le parcours International), j'ai l'erreur:
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Tue Jan 26 22:53:30 CET 2016
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by javamind** [comment]
Regression suite au fait de masquer le texte pour le catégories
