### ISSUE TITLE
a quoi correspond l'id de la production dans l'url?

### ISSUE THREAD

**Issue by acrepet** [Dev-Mind/numeric-wall#84]
quand je modifie un texte je vois son URL, par exemple : https://ewall.mines-stetienne.fr/e-wall/t/360
le 360 correspond-il à l'ID du QRCODE ?
Je ne pense pas parce que quand je vais en base de donnée production_id est null pour ce qrcode 360????

**Comment by javamind** [comment]
Si tu regardes le code source CategoryService.java 

``` java
        int cpt = 0;

        //We need to read all the pixels of the main matrix
        for (int x = 0; x < dimension; x++) {
            for (int y = 0; y < dimension; y++) {
                //We construct the target matrix : each point is a new QrCode
                if (physicalQrCode.getMatrix().get(x, y) == 1) {
                    cpt++;
                    String newUrl = categoryUrl.concat("/").concat(String.valueOf(cpt));

                    QRCode smallQrCode = qrCodeGenerator.generateQRCode(newUrl, ErrorCorrectionLevel.valueOf(qrCodeQuality));
                    QrCode qrCode = qrCodeRepository.save(
```

Tu peux voir que c'est un compteur car au moment ou les QRCode sont générés nous n'avons pas l'id. Une recherche doit se faire via URL

**Comment by acrepet** [comment]
ok, mais qu'entends-tu par "Une recherche doit se faire via URL"?

**Comment by javamind** [comment]
Une recherche dans la base de QRCode mais on n'a normalement pas à le faire

**Comment by acrepet** [comment]
Pour bien comprendre : l'ID (ex: 360 pour l'URL https://ewall.mines-stetienne.fr/e-wall/t/360)  n'est pas une PK d'une table? c'est un compteur qui n'a rien à voir. Right?

**Comment by javamind** [comment]
Yes
