### ISSUE TITLE
Sur mobile les petits Qrcode dans les grands ne se voient plus

### ISSUE THREAD

**Issue by acrepet** [Dev-Mind/numeric-wall#85]
Ils sont tout petits !
Régression, ça marchait avant ;-(

**Comment by acrepet** [comment]
![screenshot_2016-01-26-23-47-29](https://cloud.githubusercontent.com/assets/544206/12597891/74ade9e8-c487-11e5-96bc-351057504075.png)

**Comment by javamind** [comment]
Ben en mettant une marge à 3 par défaut on arrive à ce résultat
Peut être ne faut il mettre cette marge à 3 que manuellement écran par écran. 
Si tu veux changer la valeur c'est dans le fichier index.js

**Comment by acrepet** [comment]
ok

**Comment by acrepet** [comment]
pour mettre la marge à 3 manuellement c'est dans index.js????

**Comment by javamind** [comment]
Si tu changes index.js cette conf sera aceesible à tous. Je pense que c'est le mieux
Sur le poste que tu utilises pour faire tes impressions de QrCode tu spécifies une marge à 3

**Comment by javamind** [comment]
La marge est à 3 actuellement. Je pense que par défaut il faut la mettre à 1 ou 0. Comme ça ce sera sympa sur plus de devices
Si je me suis trompé et que ce n'est pas la cause du problème je corrigerai

**Comment by acrepet** [comment]
ok je comprends. Donc marge à 0 ou 1 par défaut et 3 en local (à personnaliser via l'interface web donc un non dev comme Karine peut le faire) pour les impressions... Right?

**Comment by javamind** [comment]
Oui fait le test et tiens moi au courant

**Comment by acrepet** [comment]
ok
